
# Mining algorithm to use: scrypt_cpu, scrypt_gpu, sha256_cpu, or sha256_gpu
algo = scrypt_cpu

# Number of threads for mining (use all available threads if not specified)
; threads = 0

# List of payment addresses for mining rewards.
# At least one address is required for mining. If set, 'xpub' will be ignored.
miningaddr = addr1
; miningaddr = addr2
; miningaddr = addr3

# xpub address. If not provided, you will be prompted to enter it during program execution.
# This option is ignored if 'miningaddr' is set.
; xpub = xpubxxxx

# Set to true to use testnet, false for mainnet
# testnet = false

# Pool server endpoint (hostname:port or IP:port)
pool = solo.example.com:5055

# Slow down duration between each new block.
# Set to 0 to disable the slowdown feature.
# Examples:
#   slowDownDuration = 55s    # 55 seconds
#   slowDownDuration = 2m     # 2 minutes
#   slowDownDuration = 1h     # 1 hour
#   slowDownDuration = 1m30s  # 1 minute and 30 seconds
# slowDownDuration = 10s

# Mine only blocks and exit after one cycle
# mineonce=false